name = "geckolex"
version = "1.2.0"

description = "Type Agnostic Lexer"
licences = ["MIT"]
repository = { type = "github", user = "mewfinity06", repo = "gecko-gleam" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
